---
- hosts: test
  become: true
  tasks:
     - name: Install the latest version of Apache on CentOS
       yum: name=httpd state=present
       when: ansible_os_family == "Amazon Linux"

     - name: install the latest version of Apache on Debian
       apt: name=httpd state=present
       when: ansible_os_family == "Ubuntu"
